eureka:
  client:
    register-with-eureka: false
spring:
  application:
    name: api-gateway
#  config:
#    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: country-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/countries/**
        - id: award-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/awards/**
        - id: person-service
          uri: http://localhost:8092
          predicates:
            - Path=/api/v1/people/**
        - id: identity-service
          uri: http://localhost:8093
          predicates:
            - Path=/api/v1/auth/**
server:
  port: 8222
