eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8092
spring:
  application:
    name: person-service
#  config:
#    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/PersonDB
    username: postgres
    password: postgrespass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql

